[servers]

teceon-server ansible_host=52.175.51.10 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/teceon-server_key.pem

orbax-server ansible_host=20.205.0.47 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/orbax-server_key.pem