---
- name: Teceon-orbax Application Compliance
  hosts: servers
  become: true
  gather_facts: false

  vars_files:
    - ../inventory/applications.yaml
    - ../inventory/install-tool.yaml

  tasks:
    - name: Run Application Compliance Check
      ansible.builtin.import_tasks: ../tasks/applications.yaml

    - name: Tool Installation
      ansible.builtin.import_tasks: ../tasks/install-tool.yaml
      

    - name: Generate Application Compliance Report
      ansible.builtin.import_tasks: ../tasks/report.yaml